import JExtractSwiftLib
import Testing

@Suite
struct KotlinModuleTests {

  let inputFile =
    """
    public func helloWorld()
    """

  @Test("Kotlin: module header and package")
  func kotlin_moduleHeader() throws {
    try assertOutput(
      input: inputFile,
      .kotlin,
      .java,
      expectedChunks: [
        """
        // Generated by jextract-swift
        // Swift module: SwiftModule
        """,
        """
        package com.example.swift
        """,
      ]
    )
  }

  @Test("Kotlin: module imports")
  func kotlin_moduleImports() throws {
    try assertOutput(
      input: inputFile,
      .kotlin,
      .java,
      expectedChunks: [
        """
        import org.swift.swiftkit.core.*
        import org.swift.swiftkit.core.util.*
        import org.swift.swiftkit.ffm.*
        import org.swift.swiftkit.core.annotations.*
        import java.lang.foreign.*
        import java.lang.invoke.*
        import java.util.*
        import java.nio.charset.StandardCharsets
        """,
      ]
    )
  }

  @Test("Kotlin: module object structure")
  func kotlin_moduleObject() throws {
    try assertOutput(
      input: inputFile,
      .kotlin,
      .java,
      expectedChunks: [
        """
        public object SwiftModule {
          private const val LIB_NAME: String = "SwiftModule"
          @JvmField
          val LIBRARY_ARENA: Arena = Arena.ofAuto()
        """,
        """
        @JvmStatic
        fun findOrThrow(symbol: String): MemorySegment {
          return SYMBOL_LOOKUP.find(symbol)
            .orElseThrow { UnsatisfiedLinkError("unresolved symbol: $symbol") }
        ...
        """,
        """
        @JvmField
        val SYMBOL_LOOKUP: SymbolLookup = run {
        """,
      ]
    )
  }

  @Test("Kotlin: Swift thunks are same as FFM thunks")
  func kotlin_swiftThunks() throws {
    try assertOutput(
      input: inputFile,
      .kotlin,
      .swift,
      expectedChunks: [
        """
        @_cdecl("swiftjava_SwiftModule_helloWorld")
        public func swiftjava_SwiftModule_helloWorld() {
          helloWorld()
        }
        """,
      ]
    )
  }
}
